---
- name: cli command playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: Read Configuration from Boxes
      cli_command:
        command: show run
      when: ansible_network_os is defined
      register: output

    - name: Print and Save Configuration 
      debug:
        msg: "{{ output.stdout_lines }}"
